# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 01:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameCollection',
            fields=[
                ('share_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('preferred_gender', models.CharField(choices=[(b'neutral', b'Gender Neutral'), (b'boy', b'Boy'), (b'girl', b'Girl')], default=b'neutral', max_length=8)),
                ('favourites', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('ignored', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
    ]
