# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 00:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_namecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='popularity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
